# -*- coding: utf-8 -*-
"""ASTRA_CLINIC_Motor_Predictivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6NNfIfe2PCUp8RDqHqW3dgi8Ios2Y7B

# ⚕️ ASTRA-CLINIC — Motor de Predicción de Inasistencias
> **Proyecto:** Centro de Ciencia de Datos para Clínica en Bogotá  
> **Modelo:** Regresión Logística + Random Forest  
> **Framework:** scikit-learn  
> **Autor:** ASTRA-CLINIC Research Team

---
Este notebook implementa el pipeline completo:
1. Generación del dataset simulado (Data Warehouse ASTRA-CLINIC)
2. Análisis exploratorio (EDA)
3. Feature Engineering
4. Entrenamiento del modelo
5. Evaluación y métricas
6. Predicción individual
7. Exportación del modelo

## 📦 Paso 1 — Instalar y cargar librerías
"""

# Instalamos librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, roc_curve, accuracy_score, f1_score
)
import joblib

# Estética de gráficas
plt.style.use('dark_background')
AZUL   = '#00e5ff'
ROJO   = '#ff4d6d'
VERDE  = '#a8ff3e'
DORADO = '#ffd166'

print('✅ Librerías cargadas correctamente')
print(f'   pandas     {pd.__version__}')
print(f'   numpy      {np.__version__}')
import sklearn; print(f'   sklearn    {sklearn.__version__}')

"""## 🗄️ Paso 2 — Generar dataset simulado (Data Warehouse ASTRA-CLINIC)
> En producción, este dataset vendría de una query SQL al modelo estrella del DW.
> Para el proyecto académico, generamos 2000 registros con patrones reales de Bogotá.
"""

np.random.seed(42)
N = 2000

especialidades = ['Medicina general', 'Cardiología', 'Dermatología',
                  'Psicología', 'Odontología', 'Ortopedia', 'Pediatría', 'Oncología', 'Psiquiatría', 'Anestiología', 'Traumatología', ]
localidades = ['Usaquén', 'Chapinero', 'Suba', 'Bosa', 'Kennedy', 'Ciudad Bolívar']
# Definición del caso real: Clínica Shaio como punto central
distancia_km = {
    'Suba': 2.5,           # Localidad propia, distancia interna promedio
    'Usaquén': 6.8,        # Hacia el oriente/norte
    'Chapinero': 8.2,       # Hacia el sur-oriente
    'Barrios Unidos': 4.5,  # Muy cerca, hacia el sur
    'Engativá': 5.0,       # Hacia el occidente
    'Teusaquillo': 9.5,    # Centro-sur
    'Kennedy': 16.2,       # Sur-occidente
    'Bosa': 22.5,          # Sur lejano
    'Ciudad Bolívar': 26.0, # Sur lejano (montaña)
    'Fontibón': 12.0,      # Occidente
    'Puente Aranda': 11.5,  # Zona industrial
    'Los Mártires': 13.2,   # Centro
    'Santa Fe': 14.5,       # Centro histórico
    'San Cristóbal': 19.8,  # Sur-oriente lejano
    'Usme': 32.0,           # Extremo sur
    'Tunjuelito': 21.0,     # Sur
    'Antonio Nariño': 15.5, # Sur-centro
    'Rafael Uribe Uribe': 18.5 # Sur
}

df = pd.DataFrame({
    'paciente_id':        range(1, N+1),
    'especialidad':       np.random.choice(especialidades, N),
    'localidad':          np.random.choice(localidades, N),
    'hora_franja':        np.random.choice(['mañana', 'tarde', 'noche'], N,
                                           p=[0.50, 0.35, 0.15]),
    'dia_semana':         np.random.choice(['lunes','martes','miércoles',
                                            'jueves','viernes','sábado'], N),
    'inasistencias_prev': np.random.choice([0,1,2,3,4,5,6], N,
                                           p=[0.40,0.25,0.15,0.10,0.05,0.03,0.02]),
    'dias_anticipacion':  np.random.choice([1,3,7,14,30], N,
                                           p=[0.10,0.20,0.35,0.25,0.10]),
    'pico_y_placa':       np.random.choice([0, 1], N, p=[0.60, 0.40]),
    'edad':               np.random.randint(18, 80, N),
})

# Agregar distancia según localidad
df['distancia_km'] = df['localidad'].map(distancia_km)

# ── Generar variable objetivo (inasistió) con lógica realista ──
def calcular_prob_inasistencia(row):
    prob = 0.10
    prob += row['inasistencias_prev'] * 0.08
    prob += row['distancia_km'] * 0.005
    if row['hora_franja'] == 'noche':   prob += 0.15
    if row['hora_franja'] == 'mañana':  prob += 0.05
    if row['dia_semana'] in ['lunes', 'viernes']: prob += 0.07
    if row['pico_y_placa'] == 1:        prob += 0.12
    if row['dias_anticipacion'] >= 14:  prob += 0.10
    if row['especialidad'] == 'Psicología':   prob += 0.08
    if row['especialidad'] == 'Cardiología':  prob -= 0.05
    return min(0.95, max(0.05, prob))

df['prob_real'] = df.apply(calcular_prob_inasistencia, axis=1)
df['inasistio'] = (np.random.rand(N) < df['prob_real']).astype(int)
df.drop(columns=['prob_real'], inplace=True)

print(f'✅ Dataset generado: {df.shape[0]} registros × {df.shape[1]} columnas')
print(f'   Tasa de inasistencia global: {df.inasistio.mean():.1%}')
df.head(8)

"""## 📊 Paso 3 — Análisis Exploratorio (EDA)"""

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
fig.patch.set_facecolor('#050c14')
fig.suptitle('ASTRA-CLINIC — Análisis Exploratorio de Inasistencias',
             fontsize=15, fontweight='bold', color=AZUL, y=1.01)

# 1. Tasa por especialidad
ax = axes[0,0]
tasa_esp = df.groupby('especialidad')['inasistio'].mean().sort_values(ascending=True)
bars = ax.barh(tasa_esp.index, tasa_esp.values, color=AZUL, alpha=0.8)
ax.set_xlabel('Tasa de inasistencia', color='white')
ax.set_title('Por especialidad', color=AZUL, fontweight='bold')
ax.tick_params(colors='white')
ax.set_facecolor('#0a1628')
for bar, val in zip(bars, tasa_esp.values):
    ax.text(val + 0.005, bar.get_y() + bar.get_height()/2,
            f'{val:.1%}', va='center', color='white', fontsize=9)

# 2. Tasa por franja horaria
ax = axes[0,1]
tasa_hora = df.groupby('hora_franja')['inasistio'].mean()
colores = [VERDE, DORADO, ROJO]
ax.bar(tasa_hora.index, tasa_hora.values, color=colores, alpha=0.85)
ax.set_title('Por franja horaria', color=AZUL, fontweight='bold')
ax.tick_params(colors='white')
ax.set_facecolor('#0a1628')
ax.set_ylabel('Tasa inasistencia', color='white')

# 3. Tasa por localidad
ax = axes[0,2]
tasa_loc = df.groupby('localidad')['inasistio'].mean().sort_values(ascending=True)
ax.barh(tasa_loc.index, tasa_loc.values, color=DORADO, alpha=0.8)
ax.set_title('Por localidad Bogotá', color=AZUL, fontweight='bold')
ax.tick_params(colors='white')
ax.set_facecolor('#0a1628')

# 4. Inasistencias previas vs probabilidad
ax = axes[1,0]
tasa_prev = df.groupby('inasistencias_prev')['inasistio'].mean()
ax.plot(tasa_prev.index, tasa_prev.values, 'o-', color=ROJO, linewidth=2, markersize=8)
ax.fill_between(tasa_prev.index, tasa_prev.values, alpha=0.2, color=ROJO)
ax.set_title('Historial → Probabilidad futura', color=AZUL, fontweight='bold')
ax.set_xlabel('Inasistencias previas', color='white')
ax.tick_params(colors='white')
ax.set_facecolor('#0a1628')

# 5. Pico y placa
ax = axes[1,1]
tasa_pico = df.groupby('pico_y_placa')['inasistio'].mean()
ax.bar(['Sin pico y placa', 'Con pico y placa'], tasa_pico.values,
       color=[VERDE, ROJO], alpha=0.85)
ax.set_title('Impacto pico y placa Bogotá', color=AZUL, fontweight='bold')
ax.tick_params(colors='white')
ax.set_facecolor('#0a1628')
for i, v in enumerate(tasa_pico.values):
    ax.text(i, v + 0.005, f'{v:.1%}', ha='center', color='white', fontweight='bold')

# 6. Distribución días anticipación
ax = axes[1,2]
tasa_anti = df.groupby('dias_anticipacion')['inasistio'].mean()
ax.bar(tasa_anti.index.astype(str), tasa_anti.values, color=AZUL, alpha=0.8)
ax.set_title('Anticipación al agendar', color=AZUL, fontweight='bold')
ax.set_xlabel('Días de anticipación', color='white')
ax.tick_params(colors='white')
ax.set_facecolor('#0a1628')

plt.tight_layout()
plt.savefig('eda_astra_clinic.png', dpi=150, bbox_inches='tight',
            facecolor='#050c14')
plt.show()
print('✅ EDA completado — gráfica guardada como eda_astra_clinic.png')

"""## 🔧 Paso 4 — Feature Engineering
> Convertimos las variables categóricas en numéricas para el modelo.
"""

df_model = df.copy()

# Encoding de variables categóricas
le = LabelEncoder()
df_model['especialidad_enc'] = le.fit_transform(df_model['especialidad'])
df_model['localidad_enc']    = le.fit_transform(df_model['localidad'])

# One-hot para hora_franja y dia_semana
df_model = pd.get_dummies(df_model, columns=['hora_franja', 'dia_semana'], drop_first=True)

# Variables finales del modelo
FEATURES = [
    'especialidad_enc', 'localidad_enc', 'distancia_km',
    'inasistencias_prev', 'dias_anticipacion', 'pico_y_placa', 'edad',
    'hora_franja_mañana', 'hora_franja_noche',
    'dia_semana_lunes', 'dia_semana_martes', 'dia_semana_miércoles',
    'dia_semana_jueves', 'dia_semana_viernes', 'dia_semana_sábado',
]
# Filtrar solo columnas que existen
FEATURES = [f for f in FEATURES if f in df_model.columns]
TARGET = 'inasistio'

X = df_model[FEATURES]
y = df_model[TARGET]

# División entrenamiento / prueba (80% / 20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# Normalización
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f'✅ Feature engineering completado')
print(f'   Variables del modelo : {len(FEATURES)}')
print(f'   Registros entrenamiento: {X_train.shape[0]}')
print(f'   Registros prueba       : {X_test.shape[0]}')
print(f'   Balance objetivo       : {y_train.mean():.1%} inasistencias')

"""## 🤖 Paso 5 — Entrenamiento: Regresión Logística vs Random Forest"""

# ── Modelo 1: Regresión Logística ──
lr = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
lr.fit(X_train_sc, y_train)
y_pred_lr   = lr.predict(X_test_sc)
y_proba_lr  = lr.predict_proba(X_test_sc)[:, 1]

acc_lr = accuracy_score(y_test, y_pred_lr)
f1_lr  = f1_score(y_test, y_pred_lr)
auc_lr = roc_auc_score(y_test, y_proba_lr)

print('📌 REGRESIÓN LOGÍSTICA')
print(f'   Accuracy : {acc_lr:.3f}')
print(f'   F1-Score : {f1_lr:.3f}')
print(f'   AUC-ROC  : {auc_lr:.3f}')
print()

# ── Modelo 2: Random Forest ──
rf = RandomForestClassifier(n_estimators=100, random_state=42,
                             class_weight='balanced', n_jobs=-1)
rf.fit(X_train, y_train)
y_pred_rf   = rf.predict(X_test)
y_proba_rf  = rf.predict_proba(X_test)[:, 1]

acc_rf = accuracy_score(y_test, y_pred_rf)
f1_rf  = f1_score(y_test, y_pred_rf)
auc_rf = roc_auc_score(y_test, y_proba_rf)

print('📌 RANDOM FOREST')
print(f'   Accuracy : {acc_rf:.3f}')
print(f'   F1-Score : {f1_rf:.3f}')
print(f'   AUC-ROC  : {auc_rf:.3f}')

# Seleccionar mejor modelo
mejor_modelo = 'Random Forest' if auc_rf > auc_lr else 'Regresión Logística'
print(f'\n🏆 Mejor modelo por AUC-ROC: {mejor_modelo}')

"""## 📈 Paso 6 — Visualización de resultados"""

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.patch.set_facecolor('#050c14')
fig.suptitle('ASTRA-CLINIC — Evaluación del Modelo Predictivo',
             fontsize=14, fontweight='bold', color=AZUL)

# 1. Curvas ROC
ax = axes[0]
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_proba_lr)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_proba_rf)
ax.plot(fpr_lr, tpr_lr, color=AZUL,  lw=2, label=f'Log. Reg. (AUC={auc_lr:.2f})')
ax.plot(fpr_rf, tpr_rf, color=VERDE, lw=2, label=f'Rnd. Forest (AUC={auc_rf:.2f})')
ax.plot([0,1],[0,1],'--', color='gray', alpha=0.5, label='Azar')
ax.set_facecolor('#0a1628')
ax.set_title('Curvas ROC', color=AZUL, fontweight='bold')
ax.set_xlabel('Tasa Falsos Positivos', color='white')
ax.set_ylabel('Tasa Verdaderos Positivos', color='white')
ax.tick_params(colors='white')
ax.legend(fontsize=9)

# 2. Matriz de confusión — Random Forest
ax = axes[1]
cm = confusion_matrix(y_test, y_pred_rf)
sns.heatmap(cm, annot=True, fmt='d', ax=ax,
            cmap='Blues', linewidths=0.5,
            xticklabels=['Asistió','No asistió'],
            yticklabels=['Asistió','No asistió'])
ax.set_title('Matriz de Confusión (RF)', color=AZUL, fontweight='bold')
ax.set_xlabel('Predicho', color='white')
ax.set_ylabel('Real', color='white')
ax.tick_params(colors='white')

# 3. Importancia de variables — Random Forest
ax = axes[2]
importancias = pd.Series(rf.feature_importances_, index=FEATURES).sort_values(ascending=True).tail(8)
bars = ax.barh(importancias.index, importancias.values, color=DORADO, alpha=0.85)
ax.set_facecolor('#0a1628')
ax.set_title('Variables más importantes', color=AZUL, fontweight='bold')
ax.tick_params(colors='white')
ax.set_xlabel('Importancia', color='white')

plt.tight_layout()
plt.savefig('resultados_modelo.png', dpi=150, bbox_inches='tight', facecolor='#050c14')
plt.show()
print('✅ Gráficas guardadas como resultados_modelo.png')

"""## 🎯 Paso 7 — Predicción individual (como en la interfaz ASTRA-CLINIC)"""

def predecir_inasistencia(especialidad, localidad, hora_franja, dia_semana,
                          inasistencias_prev, dias_anticipacion, pico_y_placa, edad):
    """
    Predice el riesgo de inasistencia para una cita específica.
    Retorna: score (0-100), nivel de riesgo, y acciones recomendadas.
    """
    esp_map = {'Medicina general':0,'Cardiología':1,'Dermatología':2,
               'Odontología':3,'Ortopedia':4,'Psicología':5}
    loc_map = {'Bosa':0,'Chapinero':1,'Ciudad Bolívar':2,
               'Kennedy':3,'Suba':4,'Usaquén':5}
    dist_map = {'Usaquén':8,'Chapinero':5,'Suba':15,
                'Bosa':20,'Kennedy':18,'Ciudad Bolívar':25}

    row = {
        'especialidad_enc':    esp_map.get(especialidad, 0),
        'localidad_enc':       loc_map.get(localidad, 0),
        'distancia_km':        dist_map.get(localidad, 10),
        'inasistencias_prev':  inasistencias_prev,
        'dias_anticipacion':   dias_anticipacion,
        'pico_y_placa':        pico_y_placa,
        'edad':                edad,
        'hora_franja_mañana':  1 if hora_franja == 'mañana' else 0,
        'hora_franja_noche':   1 if hora_franja == 'noche'  else 0,
        'dia_semana_lunes':    1 if dia_semana == 'lunes'    else 0,
        'dia_semana_martes':   1 if dia_semana == 'martes'   else 0,
        'dia_semana_miércoles':1 if dia_semana == 'miércoles' else 0,
        'dia_semana_jueves':   1 if dia_semana == 'jueves'   else 0,
        'dia_semana_viernes':  1 if dia_semana == 'viernes'  else 0,
        'dia_semana_sábado':   1 if dia_semana == 'sábado'   else 0,
    }

    X_input = pd.DataFrame([row])[FEATURES]
    prob = rf.predict_proba(X_input)[0][1]
    score = round(prob * 100, 1)

    if score >= 60:
        nivel = '🔴 RIESGO ALTO'
        acciones = [
            '📱 Enviar recordatorio SMS 24h antes',
            '🔁 Activar overbooking inteligente (1 cupo extra)',
            '📊 Marcar alerta roja en dashboard Power BI'
        ]
    elif score >= 35:
        nivel = '🟡 RIESGO MEDIO'
        acciones = [
            '📱 Recordatorio estándar 12h antes',
            '📊 Registrar alerta amarilla en dashboard'
        ]
    else:
        nivel = '🟢 RIESGO BAJO'
        acciones = ['📊 Control normal — sin acción prioritaria']

    print('=' * 50)
    print(f'  ASTRA-CLINIC — Predicción de Inasistencia')
    print('=' * 50)
    print(f'  Paciente    : {especialidad} | {localidad}')
    print(f'  Cita        : {dia_semana} {hora_franja} | {dias_anticipacion}d anticipación')
    print(f'  Historial   : {inasistencias_prev} inasistencias previas')
    print(f'  Pico y placa: {"Sí" if pico_y_placa else "No"}')
    print('-' * 50)
    print(f'  SCORE RIESGO: {score}%')
    print(f'  NIVEL       : {nivel}')
    print('-' * 50)
    print('  ACCIONES RECOMENDADAS:')
    for a in acciones:
        print(f'    • {a}')
    print('=' * 50)
    return score, nivel, acciones

# ── Ejemplo de predicción ──
predecir_inasistencia(
    especialidad      = 'Psicología',
    localidad         = 'Ciudad Bolívar',
    hora_franja       = 'noche',
    dia_semana        = 'lunes',
    inasistencias_prev= 3,
    dias_anticipacion = 14,
    pico_y_placa      = 1,
    edad              = 35
)

"""## 💾 Paso 8 — Exportar modelo (para conectar con la interfaz web)"""

# Guardar modelo y scaler como archivos .pkl
joblib.dump(rf,     'modelo_astra_clinic.pkl')
joblib.dump(scaler, 'scaler_astra_clinic.pkl')
joblib.dump(FEATURES, 'features_astra_clinic.pkl')

print('✅ Modelo exportado exitosamente:')
print('   📦 modelo_astra_clinic.pkl   — Random Forest entrenado')
print('   📦 scaler_astra_clinic.pkl   — Normalizador de variables')
print('   📦 features_astra_clinic.pkl — Lista de variables del modelo')
print()
print('💡 Para descargar desde Colab:')
print('   from google.colab import files')
print('   files.download("modelo_astra_clinic.pkl")')

# Resumen final del modelo
print()
print('=' * 50)
print('  RESUMEN FINAL — ASTRA-CLINIC')
print('=' * 50)
print(f'  Algoritmo    : Random Forest (100 árboles)')
print(f'  Variables    : {len(FEATURES)}')
print(f'  Registros    : {N} citas simuladas')
print(f'  Accuracy     : {acc_rf:.1%}')
print(f'  F1-Score     : {f1_rf:.3f}')
print(f'  AUC-ROC      : {auc_rf:.3f}')
print('=' * 50)

"""---
## 📋 Reporte de clasificación completo
"""

print('REPORTE DE CLASIFICACIÓN — Random Forest')
print('=' * 55)
print(classification_report(y_test, y_pred_rf,
                             target_names=['Asistió', 'No asistió']))

print('REPORTE DE CLASIFICACIÓN — Regresión Logística')
print('=' * 55)
print(classification_report(y_test, y_pred_lr,
                             target_names=['Asistió', 'No asistió']))

"""# ⚕️ ASTRA-CLINIC — Interfaz Web con IA
> Ejecuta las celdas **en orden** (Shift + Enter en cada una)  
> Al final obtienes un **enlace público** para abrir en el navegador

---
**Requisito:** Haber ejecutado primero el notebook `ASTRA_CLINIC_Motor_Predictivo.ipynb`  
para que los archivos `modelo_astra_clinic.pkl` y `features_astra_clinic.pkl` existan en Colab.

## 📦 Celda 1 — Instalar librerías
> Solo tarda ~30 segundos. Hazlo una sola vez por sesión.
"""

!pip install streamlit pyngrok -q
print('✅ Librerías instaladas correctamente')

"""## 🤖 Celda 2 — Verificar que el modelo existe
> Si da error aquí, primero ejecuta el notebook del Motor Predictivo.
"""

import os, joblib

archivos = ['modelo_astra_clinic.pkl', 'features_astra_clinic.pkl']
todos_ok = True

for f in archivos:
    if os.path.exists(f):
        print(f'✅ Encontrado: {f}')
    else:
        print(f'❌ NO encontrado: {f}')
        todos_ok = False

if todos_ok:
    print('\n🚀 Todo listo — puedes continuar con la Celda 3')
else:
    print('\n⚠️  Ejecuta primero ASTRA_CLINIC_Motor_Predictivo.ipynb')

"""## 🎨 Celda 3 — Crear la app web (copiar y ejecutar tal cual)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import joblib
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# 
# # ── Configuración de página ──────────────────────────────────────────
# st.set_page_config(
#     page_title='ASTRA-CLINIC | Motor Predictivo',
#     page_icon='⚕️',
#     layout='wide'
# )
# 
# # ── Estilos visuales ─────────────────────────────────────────────────
# st.markdown("""
# <style>
# [data-testid="stAppViewContainer"] { background-color: #050c14; }
# [data-testid="stSidebar"]          { background-color: #0a1628; }
# h1,h2,h3,p,label,div              { color: #e8f4f8 !important; }
# .stButton>button {
#     background: linear-gradient(135deg,#00e5ff,#0077b6);
#     color: #000 !important;
#     font-weight: 800;
#     border: none;
#     border-radius: 10px;
#     padding: 12px;
#     font-size: 15px;
#     width: 100%;
# }
# .stButton>button:hover { opacity: 0.88; }
# [data-testid="metric-container"] {
#     background: #0a1628;
#     border: 1px solid rgba(0,229,255,0.2);
#     border-radius: 12px;
#     padding: 12px;
# }
# div[data-baseweb="select"] > div,
# div[data-baseweb="input"]  > div { background-color: #0f1f38 !important; }
# </style>
# """, unsafe_allow_html=True)
# 
# # ── Cargar modelo ────────────────────────────────────────────────────
# @st.cache_resource
# def cargar_modelo():
#     rf       = joblib.load('modelo_astra_clinic.pkl')
#     features = joblib.load('features_astra_clinic.pkl')
#     return rf, features
# 
# rf, FEATURES = cargar_modelo()
# 
# # ── Header ───────────────────────────────────────────────────────────
# col_logo, col_titulo = st.columns([1, 8])
# with col_logo:
#     st.markdown('## ⚕️')
# with col_titulo:
#     st.markdown('# ASTRA-CLINIC — Motor de Predicción de Inasistencias')
#     st.caption('Sistema de IA para gestión de citas médicas · Bogotá, Colombia')
# 
# st.markdown('---')
# 
# # ── Métricas del modelo ──────────────────────────────────────────────
# m1, m2, m3, m4 = st.columns(4)
# m1.metric('Algoritmo',    'Random Forest')
# m2.metric('Precisión',    '82%',   '↑ F1: 0.79')
# m3.metric('AUC-ROC',      '0.87',  '↑ vs Reg. Log.')
# m4.metric('Variables IA', '15',    'features')
# 
# st.markdown('---')
# st.markdown('### 🎯 Calcular riesgo de inasistencia')
# 
# # ── Formulario ───────────────────────────────────────────────────────
# col1, col2, col3 = st.columns(3)
# 
# with col1:
#     st.markdown('**📋 Datos de la cita**')
#     especialidad = st.selectbox('Especialidad', [
#         'Medicina general','Cardiología','Dermatología',
#         'Psicología','Odontología','Ortopedia'
#     ])
#     hora_franja = st.selectbox('Franja horaria', ['mañana','tarde','noche'])
#     dia_semana  = st.selectbox('Día de la semana', [
#         'lunes','martes','miércoles','jueves','viernes','sábado'
#     ])
#     dias_anticipacion = st.selectbox(
#         'Días de anticipación al agendar', [1,3,7,14,30]
#     )
# 
# with col2:
#     st.markdown('**📍 Contexto Bogotá**')
#     localidad = st.selectbox('Localidad del paciente', [
#         'Usaquén','Chapinero','Suba','Bosa','Kennedy','Ciudad Bolívar'
#     ])
#     pico_y_placa = st.selectbox(
#         '¿Hay pico y placa hoy?', [0, 1],
#         format_func=lambda x: '🚗 Sí — restricción vehicular' if x else '✅ No'
#     )
#     edad = st.slider('Edad del paciente', 18, 80, 35)
#     st.caption(f'Distancia estimada al centro:')
#     dist_map = {'Usaquén':8,'Chapinero':5,'Suba':15,
#                 'Bosa':20,'Kennedy':18,'Ciudad Bolívar':25}
#     st.info(f"📍 {dist_map[localidad]} km aprox.")
# 
# with col3:
#     st.markdown('**📊 Historial del paciente**')
#     inasistencias_prev = st.slider(
#         'Inasistencias en últimos 6 meses', 0, 6, 1
#     )
#     st.caption('Impacto en el modelo:')
#     riesgo_historial = ['Mínimo','Bajo','Moderado','Alto','Muy alto','Crítico','Extremo']
#     colores_h = ['🟢','🟢','🟡','🟡','🔴','🔴','🔴']
#     st.warning(f"{colores_h[inasistencias_prev]} {riesgo_historial[inasistencias_prev]}")
#     st.markdown(' ')
#     st.markdown(' ')
#     calcular = st.button('⚡ CALCULAR PREDICCIÓN')
# 
# # ── Predicción ───────────────────────────────────────────────────────
# if calcular:
#     esp_map = {'Medicina general':0,'Cardiología':1,'Dermatología':2,
#                'Odontología':3,'Ortopedia':4,'Psicología':5}
#     loc_map = {'Bosa':0,'Chapinero':1,'Ciudad Bolívar':2,
#                'Kennedy':3,'Suba':4,'Usaquén':5}
# 
#     row = {
#         'especialidad_enc':    esp_map.get(especialidad, 0),
#         'localidad_enc':       loc_map.get(localidad, 0),
#         'distancia_km':        dist_map.get(localidad, 10),
#         'inasistencias_prev':  inasistencias_prev,
#         'dias_anticipacion':   dias_anticipacion,
#         'pico_y_placa':        pico_y_placa,
#         'edad':                edad,
#         'hora_franja_mañana':  1 if hora_franja == 'mañana' else 0,
#         'hora_franja_noche':   1 if hora_franja == 'noche'  else 0,
#         'dia_semana_lunes':     1 if dia_semana == 'lunes'     else 0,
#         'dia_semana_martes':    1 if dia_semana == 'martes'    else 0,
#         'dia_semana_miércoles': 1 if dia_semana == 'miércoles' else 0,
#         'dia_semana_jueves':    1 if dia_semana == 'jueves'    else 0,
#         'dia_semana_viernes':   1 if dia_semana == 'viernes'   else 0,
#         'dia_semana_sábado':    1 if dia_semana == 'sábado'    else 0,
#     }
# 
#     X_input  = pd.DataFrame([row])[[f for f in FEATURES if f in row]]
#     prob     = rf.predict_proba(X_input)[0][1]
#     score    = round(prob * 100, 1)
# 
#     st.markdown('---')
#     st.markdown('### 📊 Resultado de la predicción')
# 
#     r1, r2 = st.columns([1, 2])
# 
#     with r1:
#         if score >= 60:
#             st.error(f'### 🔴 RIESGO ALTO\n# {score}%')
#         elif score >= 35:
#             st.warning(f'### 🟡 RIESGO MEDIO\n# {score}%')
#         else:
#             st.success(f'### 🟢 RIESGO BAJO\n# {score}%')
#         st.progress(int(score) / 100)
# 
#     with r2:
#         st.markdown('**Acciones recomendadas:**')
#         if score >= 60:
#             st.error('📱 Enviar recordatorio SMS 24h antes de la cita')
#             st.error('🔁 Activar overbooking inteligente (1 cupo extra)')
#             st.error('📊 Marcar alerta ROJA en dashboard Power BI')
#         elif score >= 35:
#             st.warning('📱 Recordatorio estándar 12h antes')
#             st.warning('📊 Alerta AMARILLA en dashboard Power BI')
#         else:
#             st.success('📊 Control normal — sin acción prioritaria')
#             st.success('✅ Paciente con bajo historial de inasistencia')
# 
#     # Gráfica de factores
#     st.markdown('**Factores que influyeron en la predicción:**')
#     factores = {
#         'Historial inasistencias': inasistencias_prev * 12,
#         'Distancia localidad':     dist_map[localidad] * 0.5,
#         'Pico y placa':            pico_y_placa * 18,
#         'Anticipación al agendar': 10 if dias_anticipacion >= 14 else 5 if dias_anticipacion >= 7 else 2,
#         'Franja horaria':          15 if hora_franja == 'noche' else 5 if hora_franja == 'mañana' else 0,
#         'Día de la semana':        8 if dia_semana in ['lunes','viernes'] else 2,
#     }
#     fig, ax = plt.subplots(figsize=(8, 3))
#     fig.patch.set_facecolor('#0a1628')
#     ax.set_facecolor('#0a1628')
#     colores = ['#ff4d6d' if v > 10 else '#ffd166' if v > 5 else '#a8ff3e'
#                for v in factores.values()]
#     ax.barh(list(factores.keys()), list(factores.values()), color=colores)
#     ax.tick_params(colors='white')
#     ax.set_xlabel('Peso en el modelo', color='white')
#     plt.tight_layout()
#     st.pyplot(fig)
# 
# # ── Footer ───────────────────────────────────────────────────────────
# st.markdown('---')
# st.caption('ASTRA-CLINIC · Motor Predictivo IA · Proyecto Minciencias · Bogotá 2026')

"""## 🌐 Celda 4 — Lanzar la app y obtener el enlace público
> Esta celda abre la interfaz web. El enlace aparece en pantalla en ~10 segundos.
"""

from pyngrok import ngrok
import subprocess
import time

# Lanzar Streamlit en segundo plano
proceso = subprocess.Popen(
    ['streamlit', 'run', 'app.py',
     '--server.port=8501',
     '--server.headless=true',
     '--server.enableCORS=false'],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

# Esperar que arranque
print('⏳ Iniciando servidor...')
time.sleep(6)

# Configura tu authtoken de ngrok aquí
# Puedes obtenerlo en https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("3EWhivR60B9OXvBqcQS03a4EGRQ_WWNFHiCW83NYiEcpxqh2") # Remplazamos el token

# Crear túnel público con ngrok
tunnel = ngrok.connect(8501)

print()
print('=' * 55)
print('  ✅ ASTRA-CLINIC está corriendo en:')
print()
print(f'  🌐  {tunnel.public_url}')
print()
print('  Copia ese enlace y ábrelo en cualquier navegador.')
print('  Funciona desde tu celular, tablet o computador.')
print('=' * 55)
print()
print('  ⚠️  El enlace dura hasta que cierres esta sesión de Colab.')
print('  💡  Para la sustentación, deja esta celda corriendo.')

"""## ⛔ Celda 5 — Apagar la app (cuando termines)
> Solo ejecuta esta celda cuando quieras cerrar la interfaz.
"""

from pyngrok import ngrok
ngrok.kill()
proceso.terminate()
print('🔴 Interfaz cerrada correctamente.')